=== lukasz-golebiewski/utafx/jaxb-preferences/src/main/resources/uta_prefs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="preferences">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="criteria" type="criteria" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="alternatives" type="alternatives"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="refRank" type="refRank" minOccurs="0"
					maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="generated" type="xs:date" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="criteria">
		<xs:sequence>
			<xs:element name="criterion" type="criterion" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="criterion">
		<xs:sequence>
			<xs:element name="ordinals" type="ordinals" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="criteriaType" use="required" />
		<xs:attribute name="segments" type="segmentType" use="optional"
			default="2" />
	</xs:complexType>

	<xs:simpleType name="segmentType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="2" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ordinals">
		<xs:sequence>
			<xs:element name="ordinal" type="ordinal" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ordinal">
		<xs:attribute name="rank" type="xs:int" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:simpleType name="criteriaType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gain" />
			<xs:enumeration value="cost" />
			<xs:enumeration value="ordinal" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="alternatives">
		<xs:sequence>
			<xs:element name="alternative" type="alternative"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="alternative">
		<xs:sequence>
			<xs:element name="values" type="altValues" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="altValues">
		<xs:sequence>
			<xs:element name="value" type="value" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="value">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:int" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="refRank">
		<xs:sequence>
			<xs:element name="item" type="rrItem" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rrItem">
		<xs:attribute name="id" use="required" type="xs:int" />
		<xs:attribute name="rank" use="required" type="xs:int" />
	</xs:complexType>
</xs:schema>

=== lukasz-golebiewski/utafx/UtaFX/resources/real_data.xml
<?xml version="1.0" encoding="UTF-8"?>

<preferences xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="uta_prefs.xsd">
	<criteria>
		<criterion id="0" name="prize" type="cost" />
		<criterion id="1" name="time" type="cost"  segments="3"/>
		<criterion id="2" name="comfort" type="gain" segments="3"/>
	</criteria>
	<alternatives>
		<alternative name="Rer" id="0">
			<values>
				<value id="0">3</value>
				<value id="1">10</value>
				<value id="2">1</value>
			</values>
		</alternative>
		<alternative name="Metro1" id="1">
			<values>
				<value id="0">4</value>
				<value id="1">20</value>
				<value id="2">2</value>
			</values>
		</alternative>
		<alternative name="Metro2" id="2">
			<values>
				<value id="0">2</value>
				<value id="1">20</value>
				<value id="2">0</value>
			</values>
		</alternative>
		<alternative name="Bus" id="3">
			<values>
				<value id="0">6</value>
				<value id="1">40</value>
				<value id="2">0</value>
			</values>
		</alternative>
		<alternative name="Taxi" id="4">
			<values>
				<value id="0">30</value>
				<value id="1">30</value>
				<value id="2">3</value>
			</values>
		</alternative>
	</alternatives>
	
	<refRank>
		<item id="0" rank="1" />
		<item id="1" rank="2" />
		<item id="2" rank="2" />
		<item id="3" rank="3" />
		<item id="4" rank="4" />
	</refRank>
	
</preferences>
